module.exports = word = {
  "Sport and Fitness": [
    "Basketball",
    "Volleyball",
    "Decathlon",
    "Professional",
    "Championship",
    "Endurance",
    "Gymnastics",
    "Handball",
    "Penalty Kick",
    "Quarterback",
    "Racketball",
    "Skateboarding",
    "Synchronized Skating",
    "Weightlifting",
    "Water Polo",
    "Grandmaster",
    "Sportsmanship",
    "Parkour",
    "Freestyle",
    "Curling",
    "Penalty Shootout",
    "Penalty Box",
  ],
  Celebrities: [
    "Beyoncé",
    "Tom Hanks",
    "Rihanna",
    "Cristiano Ronaldo",
    "Emma Watson",
    "Leonardo DiCaprio",
    "Oprah Winfrey",
    "Jackie Chan",
    "Shakira",
    "Ariana Grande",
    "Elon Musk",
    "Angelina Jolie",
    "The Beatles",
    "Michael Jackson",
    "Barack Obama",
    "Stephen Hawking",
    "Scarlett Johansson",
    "Morgan Freeman",
    "Jennifer Lopez",
    "Lewis Hamilton",
    "BTS",
    "Meryl Streep",
    "Kim Kardashian",
    "Amitabh Bachchan",
    "Taylor Swift",
    "Paulo Coelho",
    "Jennifer Lawrence",
    "Brad Pitt",
    "Sandra Bullock",
    "Vin Diesel",
    "Jackie Robinson",
    "Serena Williams",
    "Lionel Messi",
    "Stephen Curry",
    "Lewis Capaldi",
    "Billie Eilish",
    "Kendrick Lamar",
    "Lady Gaga",
    "Quentin Tarantino",
    "Steven Spielberg",
    "Meryl Streep",
    "Tom Hanks",
    "Leonardo DiCaprio",
    "Emma Watson",
    "JK Rowling",
    "Stephen King",
    "Margaret Atwood",
    "Pablo Picasso",
    "Vincent van Gogh",
    "Frida Kahlo",
    "David Beckham",
    "Neymar",
  ],
  "Food and Beverages": [
    "Escargot",
    "Kimchi",
    "Falafel",
    "Paella",
    "Pho",
    "Hummus",
    "Gnocchi",
    "Jerk Chicken",
    "Croissants",
    "Matcha",
    "Empanadas",
    "Couscous",
    "Guacamole",
    "Quinoa",
    "Naan",
    "Miso",
    "Edamame",
    "Baklava",
    "Kombucha",
    "Champagne",
    "Espresso",
    "Chai",
    "Latte",
  ],
  "Famous Places": [
    "Melbourne",
    "Buenos Aires",
    "San Francisco",
    "Washington D.C.",
    "Saint Petersburg",
    "Johannesburg",
    "Guangzhou",
    "Los Angeles",
    "Yokohama",
    "Southampton",
    "Auckland",
    "Queensland",
    "Azerbaijan",
    "Madagascar",
    "Netherlands",
    "United Kingdom",
    "Democratic Republic of the Congo",
    "Istanbul",
    "Montevideo",
    "Chandigarh",
    "Wellington",
    "Tasmania",
  ],
  "TV and Movies": [
    "Game of Thrones",
    "Breaking Bad",
    "Friends",
    "The Office",
    "The Simpsons",
    "The Lord of the Rings trilogy",
    "The Shawshank Redemption",
    "The Godfather",
    "The Lion King",
    "The Dark Knight",
    "The Matrix",
    "Pulp Fiction",
    "Schindler's List",
    "Forrest Gump",
    "Inception",
    "The Good, the Bad and the Ugly",
    "The Silence of the Lambs",
    "Parasite",
    "Spirited Away",
    "The Grand Budapest Hotel",
    "Casablanca",
    "Fight Club",
    "Good Will Hunting",
    "The Shawshank Redemption",
    "The Godfather Part II",
    "12 Angry Men",
    "Schindler's List",
    "The Lord of the Rings: Return of the King",
    "The Dark Knight",
    "The Pulp Fiction",
    "The Social Network",
    "Whiplash",
    "Interstellar",
    "The Departed",
    "The Big Lebowski",
    "The Shining",
    "The Princess Bride",
    "Raiders of the Lost Ark",
    "Back to the Future",
    "The Empire Strikes Back",
    "The Incredibles",
    "The Grand Budapest Hotel",
    "Inception",
    "Django Unchained",
    "The Good, the Bad and the Ugly",
    "Seven Samurai",
    "The Life Aquatic with Steve Zissou",
    "Eternal Sunshine of the Spotless Mind",
    "Snatch",
    "Good Will Hunting",
    "The Grand Budapest Hotel",
    "The Big Lebowski",
    "The Princess Bride",
    "The Grand Budapest Hotel",
  ],
  "Historical Figures": [
    "Leonardo da Vinci",
    "Cleopatra VII",
    "Julius Caesar",
    "Genghis Khan",
    "William Shakespeare",
    "Napoleon Bonaparte",
    "Abraham Lincoln",
    "Marie Curie",
    "Nelson Mandela",
    "Albert Einstein",
    "Martin Luther King Jr.",
    "Leonardo da Vinci",
    "Joan of Arc",
    "Queen Elizabeth I",
    "Gutenberg",
    "Confucius",
    "Imhotep",
    "Alexander the Great",
    "Cleopatra VII",
    "Genghis Khan",
    "William Shakespeare",
    "Genghis Khan",
    "Sun Tzu",
    "Sacagawea",
    "Marie Curie",
    "Guttenberg",
    "Leonardo da Vinci",
    "Galileo Galilei",
    "Isaac Newton",
    "Marco Polo",
    "The Wright Brothers",
    "Harriet Tubman",
    "Charles Darwin",
    "Nikola Tesla",
    "Marie Curie",
    "Sigmund Freud",
    "Anne Frank",
    "Alan Turing",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Rosa Parks",
    "Winston Churchill",
    "Franklin D. Roosevelt",
    "Malala Yousafzai",
    "Leonardo da Vinci",
    "Marie Curie",
    "Albert Einstein",
    "Confucius",
  ],
};
