module.exports = word = {
  "Sport and Fitness": [
    "Basketball",
    "Volleyball",
    "Decathlon",
    "Professional",
    "Championship",
    "Endurance",
    "Gymnastics",
    "Handball",
    "Penalty Kick",
    "Quarterback",
    "Racketball",
    "Skateboarding",
    "Synchronized Skating",
    "Weightlifting",
    "Water Polo",
    "Grandmaster",
    "Sportsmanship",
    "Parkour",
    "Freestyle",
    "Curling",
    "Penalty Shootout",
    "Penalty Box",
  ],
  Celebrities: [
    "Beyonce",
    "Tom Hanks",
    "Rihanna",
    "Cristiano Ronaldo",
    "Emma Watson",
    "Leonardo DiCaprio",
    "Oprah Winfrey",
    "Jackie Chan",
    "Shakira",
    "Ariana Grande",
    "Elon Musk",
    "Angelina Jolie",
    "Michael Jackson",
    "Barack Obama",
    "Stephen Hawking",
    "Scarlett Johansson",
    "Morgan Freeman",
    "Jennifer Lopez",
    "Lewis Hamilton",
    "Meryl Streep",
    "Kim Kardashian",
    "Amitabh Bachchan",
    "Taylor Swift",
  ],
  "Food and Beverages": [
    "Escargot",
    "Kimchi",
    "Falafel",
    "Paella",
    "Pho",
    "Hummus",
    "Gnocchi",
    "Jerk Chicken",
    "Croissants",
    "Matcha",
    "Empanadas",
    "Couscous",
    "Guacamole",
    "Quinoa",
    "Naan",
    "Miso",
    "Edamame",
    "Baklava",
    "Kombucha",
    "Champagne",
    "Espresso",
    "Chai",
    "Latte",
  ],
  "Famous Places": [
    "Melbourne",
    "Buenos Aires",
    "San Francisco",
    "Washington D.C.",
    "Saint Petersburg",
    "Johannesburg",
    "Guangzhou",
    "Los Angeles",
    "Yokohama",
    "Southampton",
    "Auckland",
    "Queensland",
    "Azerbaijan",
    "Madagascar",
    "Netherlands",
    "United Kingdom",
    "Democratic Republic of the Congo",
    "Istanbul",
    "Montevideo",
    "Chandigarh",
    "Wellington",
    "Tasmania",
  ],
};
