const word = {
  celebrities: [
    "Beyonce",
    "Tom Hanks",
    "Rihanna",
    "Cristiano Ronaldo",
    "Emma Watson",
    "Leonardo DiCaprio",
    "Oprah Winfrey",
    "Jackie Chan",
    "Shakira",
    "Ariana Grande",
    "Elon Musk",
    "Angelina Jolie",
    "Michael Jackson",
    "Barack Obama",
    "Stephen Hawking",
    "Scarlett Johansson",
    "Morgan Freeman",
    "Jennifer Lopez",
    "Lewis Hamilton",
    "Meryl Streep",
    "Kim Kardashian",
    "Amitabh Bachchan",
    "Taylor Swift",
  ],
  food: [
    "Escargot",
    "Kimchi",
    "Falafel",
    "Paella",
    "Pho",
    "Hummus",
    "Gnocchi",
    "Jerk Chicken",
    "Croissants",
    "Matcha",
    "Empanadas",
    "Couscous",
    "Guacamole",
    "Quinoa",
    "Naan",
    "Miso",
    "Edamame",
    "Baklava",
    "Kombucha",
    "Champagne",
    "Espresso",
    "Chai",
    "Latte",
  ],
  locations: [
    "Melbourne",
    "Buenos Aires",
    "San Francisco",
    "Washington D.C.",
    "Saint Petersburg",
    "Johannesburg",
    "Guangzhou",
    "Los Angeles",
    "Yokohama",
    "Southampton",
    "Auckland",
    "Queensland",
    "Azerbaijan",
    "Madagascar",
    "Netherlands",
    "United Kingdom",
    "Democratic Republic of the Congo",
    "Istanbul",
    "Montevideo",
    "Chandigarh",
    "Wellington",
    "Tasmania",
  ],
};
